apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: roboshop
  namespace: argocd
spec:
  generators:
    - list:
        elements:{{- toYaml .Values.appValues }}
  template:
    metadata:
      name: 'roboshop-{{`{{appName}}`}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/gowthambabu8/argocd-guestbook.git
        targetRevision: main
        path: '{{`{{appName}}`}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{namespace}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true