apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: roboshop
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app-name: guestbook
            namespace: roboshop
          - app-name: guestbook-prod
            namespace: roboshop-prod
  template:
    metadata:
      name: 'roboshop-{{app-name}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/gowthambabu8/argocd-guestbook.git
        targetRevision: main
        path: '{{app-name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true