name: "01-Hello World"
on:
  workflow_dispatch:
jobs:
  say-hello-from-bash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world from bash"
  
  say-hello-from-python:
    runs-on:  ubuntu-24.04
    steps:
      - run: print("Hello Wordl from python")
        shell: python
  
  say-hello-from-actions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: "from actions in github marketplace"
  
  say-hello-from-taskfile:
    runs-on: ubuntu-24.04
    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
      
      - name: Hello World from taskfile
        run: task -d taskfiles hello