name: 03-triggers
on:
  push:
    branches:
      - main
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    paths:
      - "03-core-feature/filters/*.md"
      - "!03-core-feature/filters/*.txt"
    
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:
  echo-event:
    runs-on: ubuntu-24.04
    steps:
      - name: Dump full event json
        run: | 
            echo "=== $GITHUB_EVENT_NAME ==="
            cat $GITHUB_EVENT_PATH
  
