name: 04-env-variables
on:
  workflow_dispatch:

env:
  ENV_VAR: "I am set at ENV Level"

jobs:
  job-1:
    runs-on: ubuntu-24.04
    env:
      JOBS_VAR: "I am set at JOB Level"
    steps:
      - name: execute step-1 from job-1
        env:
          STEP_VAR: "I am set at STEP level"
        run: |
          echo "Env Variables : ${ENV_VAR}"
          echo "Job Variables : ${JOB_VAR}"
          echo "Step Variables : ${STEP_VAR}"
      
      - name: execute step-2 from job-1
        run: |
          echo "Env Variables : ${ENV_VAR}"
          echo "Job Variables : ${JOB_VAR}"
          echo "Step Variables : ${STEP_VAR}"
  job-2:
    runs-on: ubuntu-24.04
    steps:
      - name: execute step-1 from job-2
        run: |
          echo "Env Variables : ${ENV_VAR}"
          echo "Job Variables : ${JOB_VAR}"
          echo "Step Variables : ${STEP_VAR}"
