name: 05-passing-data
on:
  workflow_dispatch:

jobs:
  producer:
    runs-on: ubuntu-24.04
    outputs:
      foo: ${{ steps.generator-foo.outputs.foo }}
    steps:
      - name: Generate outputs and env level variables data
        id: generator-foo
        run: |
          foo=bar
          # set output ( for job output )
          echo "foo_output=$foo" >> $GITHUB_OUTPUT

          # set env variable
          echo "foo_env=$foo" >> $GITHUB_ENV
      
      - name: read variables data
        run: |
          echo "outputs at job level :: ${{ steps.generator-foo.outputs.foo }}"
          echo "env variables :: $foo_output"
  
  consumer:
    runs-on: ubuntu-24.04
    needs: producer
    steps:
      - name: get data from previous job
        run: |
          echo "foo_output from previous job :: ${{ needs.producer.outputs.foo_env }}"
          echo "foo_env :: $foo_env"
