name: 06-secrets-variables
on:
  workflow_dispatch:
    
jobs:
  secret_job:
    runs-on: ubuntu-24.04
    environment: staging
    env:
      example_repo_secret: ${{ secrets.ACCESS }}
      example_repo_variable: ${{ vars.ACCESS_ENV }}
    steps:
      - name: capture staging secret and env variables
        run: |
          echo "Repo Secret :: $example_repo_secret "
          echo "Repo Secret variable :: $example_repo_variable"
