name: Generate ASCII 
on: 
  workflow_dispatch:
    
jobs:
  ascii_pattern:
    runs-on: ubuntu-latest
    steps:
      - name: code Checkout
        uses: actions/checkout@v5.0.0
      
      - name: list files
        run: ls -ltra
        
      - name: Install cowsay
        run: ./ascii-shell.sh
