name: kk-12-secrets-variables
on:
  # schedule:
  #   - cron: "*/1 * * * *"
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: busy-box
jobs:
  docker:  
    runs-on: ubuntu-24.04
    steps:
      - name: Docker build
        run: echo docker build  -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
      
      - name: Docker Login
        run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker publish
        run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
  
  deploy:
    runs-on: ubuntu-24.04
    needs: docker
    concurrency:
        group: prod-deploy
        cancel-in-progress: false
    steps:
      - name: Docker run
        timeout-minutes: 1
        run: | 
          echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          sleep 300s