name: Passing outputs across steps
on: ["push","workflow_dispatch"]
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: print version
        id: ver
        run: |
          echo "v=1.2.3" >> "$GITHUB_OUTPUT"
          echo "project_env=DEV" >> "$GITHUB_ENV"
      - name: previous version
        id: ver2
        run: |
          echo "previous version is ${{ steps.ver.outputs.v }}"
          echo "environment is $project_env"